export const INDEXER_BASE_URL = import.meta.env.VITE_INDEXER_BASE_URL;
export const RECURRING_EXECUTOR_CONTRACT_ADDRESS = import.meta.env
  .VITE_RECURRING_EXECUTOR_CONTRACT_ADDRESS;
export const EXECUTOR_ADDRESS = import.meta.env.VITE_EXECUTOR_ADDRESS;
